version: '3.8'
services:
  fluent-bit:
    image: fluent/fluent-bit:2.1.8
    container_name: fluent-bit
    restart: always
    # network_mode: host
    volumes:
    - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

