version: '3.8'
services:
  # https://github.com/pantsel/konga/issues/462#issuecomment-633209833
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      # For use build-in filesystem db,
      # Konga creator said `I've done it with no problems on production environments.`
      # But the default `sails-disk` adapter is not designed for use as a production database;
      - NODE_ENV=development
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - ./konga_data:/app/kongadata

