# Before start
# mkdir -p prometheus_data
# chown -R 65534:65534 prometheus_data

version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    restart: always
    # network_mode: host
    container_name: prometheus
    command:
      - --config.file=/conf/prometheus.yml
      - --storage.tsdb.retention=90d
      - --web.listen-address=0.0.0.0:9090
      - --web.enable-lifecycle
    volumes:
      - ./conf/prometheus.yml:/conf/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - 127.0.0.1:9090:9090

# reload prometheus config
# docker exec prometheus kill -HUP 1
